// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaDigitalApi.Context;

#nullable disable

namespace SalaDigitalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250902010600_SeedAlunos")]
    partial class SeedAlunos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SalaDigitalApi.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "maria.silva@email.com",
                            Idade = 20,
                            Nome = "Maria Silva"
                        },
                        new
                        {
                            Id = 2,
                            Email = "joao.pereira@email.com",
                            Idade = 22,
                            Nome = "João Pereira"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ana.souza@email.com",
                            Idade = 19,
                            Nome = "Ana Souza"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
